# Generated by Django 5.1.4 on 2025-01-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('slug', models.SlugField()),
                ('spec_theme', models.CharField(max_length=100)),
                ('spec_paper', models.CharField(max_length=100)),
                ('spec_pages', models.CharField(max_length=100)),
                ('spec_front', models.CharField(max_length=100)),
                ('spec_back', models.CharField(max_length=100)),
                ('spec_bind', models.CharField(max_length=100)),
            ],
        ),
    ]
