# Generated by Django 5.1.4 on 2025-01-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holmescraftsuk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
