# Generated by Django 5.1.4 on 2025-01-25 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holmescraftsuk', '0002_alter_notebook_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notebook',
            old_name='spec_back',
            new_name='front_img',
        ),
        migrations.RenameField(
            model_name='notebook',
            old_name='spec_bind',
            new_name='page_img',
        ),
        migrations.RenameField(
            model_name='notebook',
            old_name='spec_front',
            new_name='theme',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='spec_pages',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='spec_paper',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='spec_theme',
        ),
    ]
