# Generated by Django 5.1.4 on 2025-01-25 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holmescraftsuk', '0003_rename_spec_back_notebook_front_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotebookImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_cover', models.ImageField(upload_to='images')),
                ('front_cover', models.ImageField(upload_to='images')),
                ('back_cover', models.ImageField(upload_to='images')),
                ('inside_front', models.ImageField(upload_to='images')),
                ('inside_back', models.ImageField(upload_to='images')),
                ('middle', models.ImageField(upload_to='images')),
                ('zoom_middle', models.ImageField(upload_to='images')),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holmescraftsuk.notebook')),
            ],
            options={
                'verbose_name_plural': 'Notebook images',
            },
        ),
    ]
