# Generated by Django 5.1.4 on 2025-01-25 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holmescraftsuk', '0004_notebookimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('slug', models.SlugField(blank=True, default='')),
                ('in_store', models.BooleanField(default=True)),
                ('has_variants', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='notebookimg',
            name='notebook',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='holmescraftsuk.notebook'),
        ),
        migrations.CreateModel(
            name='CardImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wide_img', models.ImageField(upload_to='images')),
                ('tall_img', models.ImageField(upload_to='images')),
                ('small_img', models.ImageField(upload_to='images')),
                ('inside_img', models.ImageField(null=True, upload_to='images')),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='holmescraftsuk.card')),
            ],
            options={
                'verbose_name_plural': 'Card images',
            },
        ),
        migrations.CreateModel(
            name='CardVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=100)),
                ('variant_img', models.ImageField(upload_to='images')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='holmescraftsuk.card')),
            ],
            options={
                'verbose_name_plural': 'Card variants',
            },
        ),
    ]
