# Generated by Django 5.1.4 on 2025-01-25 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holmescraftsuk', '0005_card_alter_notebookimg_notebook_cardimg_cardvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='price',
            field=models.FloatField(),
        ),
    ]
