# Generated by Django 5.1.4 on 2025-01-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holmescraftsuk', '0006_alter_card_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(default='Birthday', max_length=100),
        ),
    ]
