# Generated by Django 5.1.4 on 2025-01-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holmescraftsuk', '0007_card_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cardimg',
            name='inside_img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
