# Generated by Django 5.1.4 on 2025-01-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holmescraftsuk', '0008_card_code_alter_card_card_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notebook',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='code',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cardimg',
            name='small_img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='cardimg',
            name='tall_img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='cardimg',
            name='wide_img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
