# Generated by Django 5.1.4 on 2025-01-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holmescraftsuk', '0009_card_is_featured_notebook_is_featured_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
