# Generated by Django 5.1.4 on 2025-01-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holmescraftsuk', '0010_classtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='card',
            name='class_tags',
            field=models.ManyToManyField(to='holmescraftsuk.classtag'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='class_tags',
            field=models.ManyToManyField(to='holmescraftsuk.classtag'),
        ),
    ]
