# Generated by Django 5.1.4 on 2025-01-29 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holmescraftsuk', '0011_remove_card_is_featured_remove_notebook_is_featured_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassTag',
            new_name='Featured',
        ),
        migrations.AlterModelOptions(
            name='featured',
            options={'verbose_name_plural': 'Featured'},
        ),
        migrations.RemoveField(
            model_name='card',
            name='class_tags',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='class_tags',
        ),
        migrations.AddField(
            model_name='card',
            name='featured',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_cards', to='holmescraftsuk.featured'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='featured',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_notebooks', to='holmescraftsuk.featured'),
        ),
    ]
