# Generated by Django 5.1.4 on 2025-01-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holmescraftsuk', '0012_rename_classtag_featured_alter_featured_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='card',
            name='featured',
        ),
        migrations.AddField(
            model_name='card',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notebook',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Featured',
        ),
    ]
