# Generated by Django 5.1.4 on 2025-01-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holmescraftsuk', '0013_remove_notebook_featured_remove_card_featured_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('is_card', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Navbar pages',
            },
        ),
    ]
