# Generated by Django 5.1.4 on 2025-01-31 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holmescraftsuk', '0014_navbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
