# Generated by Django 5.1.4 on 2025-02-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holmescraftsuk', '0015_navbar_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
