# Generated by Django 5.1.4 on 2025-02-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holmescraftsuk', '0016_alter_card_price_alter_notebook_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='code',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
