# Generated by Django 5.2.5 on 2025-08-19 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holmescraftsuk', '0017_notebook_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardvariant',
            name='card',
        ),
        migrations.RemoveField(
            model_name='cardimg',
            name='card',
        ),
        migrations.DeleteModel(
            name='Navbar',
        ),
        migrations.RemoveField(
            model_name='notebookimg',
            name='notebook',
        ),
        migrations.DeleteModel(
            name='CardVariant',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='CardImg',
        ),
        migrations.DeleteModel(
            name='Notebook',
        ),
        migrations.DeleteModel(
            name='NotebookImg',
        ),
    ]
