# Generated by Django 5.2.5 on 2025-08-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('is_card', models.BooleanField()),
                ('slug', models.SlugField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Navbar pages',
                'ordering': ['order'],
            },
        ),
    ]
