# Generated by Django 5.2.5 on 2025-08-22 18:06

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, editable=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('slug', models.SlugField(blank=True, default='')),
                ('code', models.CharField(max_length=20, null=True, unique=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('in_store', models.BooleanField(default=True)),
                ('has_variants', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PriceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, editable=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, editable=False)),
                ('name', models.CharField(max_length=20)),
                ('orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=10)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.product')),
                ('card_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='catalog.cardtype')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
            bases=('catalog.product',),
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.product')),
                ('theme', models.CharField(max_length=100)),
                ('page_img', models.CharField(max_length=100)),
                ('front_img', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
            bases=('catalog.product',),
        ),
        migrations.CreateModel(
            name='CardInsert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('picture', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to=catalog.models.upload_to)),
                ('card_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_inserts', to='catalog.cardtype')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='price_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.pricegroup'),
        ),
        migrations.AddField(
            model_name='pricegroup',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.producttype'),
        ),
        migrations.AddField(
            model_name='pricegroup',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.tag'),
        ),
        migrations.CreateModel(
            name='CardVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, editable=False)),
                ('variant_name', models.CharField(max_length=100)),
                ('variant_img', models.ImageField(upload_to=catalog.models.upload_to)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.card')),
            ],
            options={
                'verbose_name_plural': 'Card variants',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CardImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wide_img', models.ImageField(blank=True, null=True, upload_to=catalog.models.upload_to)),
                ('tall_img', models.ImageField(blank=True, null=True, upload_to=catalog.models.upload_to)),
                ('small_img', models.ImageField(blank=True, null=True, upload_to=catalog.models.upload_to)),
                ('inside_img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='catalog.cardinsert')),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.card')),
            ],
            options={
                'verbose_name_plural': 'Card images',
            },
        ),
        migrations.CreateModel(
            name='NotebookImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_cover', models.ImageField(upload_to=catalog.models.upload_to)),
                ('front_cover', models.ImageField(upload_to=catalog.models.upload_to)),
                ('inside_front', models.ImageField(upload_to=catalog.models.upload_to)),
                ('inside_back', models.ImageField(upload_to=catalog.models.upload_to)),
                ('middle', models.ImageField(upload_to=catalog.models.upload_to)),
                ('notebook', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.notebook')),
            ],
            options={
                'verbose_name_plural': 'Notebook images',
            },
        ),
    ]
