# Generated by Django 5.2.5 on 2025-08-19 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slug', models.SlugField(blank=True, default='')),
                ('in_store', models.BooleanField(default=True)),
                ('has_variants', models.BooleanField(default=False)),
                ('card_type', models.CharField(choices=[('birthday', 'Birthday'), ('wedding', 'Wedding & Anniversary'), ('seasonal', 'Seasonal'), ('special', 'Special Occasions'), ('other', 'Other')], max_length=100)),
                ('code', models.CharField(max_length=10, null=True, unique=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slug', models.SlugField(blank=True, default='')),
                ('theme', models.CharField(max_length=100)),
                ('page_img', models.CharField(max_length=100)),
                ('front_img', models.CharField(max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=20, null=True, unique=True)),
                ('order', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CardImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wide_img', models.ImageField(blank=True, null=True, upload_to='images')),
                ('tall_img', models.ImageField(blank=True, null=True, upload_to='images')),
                ('small_img', models.ImageField(blank=True, null=True, upload_to='images')),
                ('inside_img', models.ImageField(blank=True, null=True, upload_to='images')),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.card')),
            ],
            options={
                'verbose_name_plural': 'Card images',
            },
        ),
        migrations.CreateModel(
            name='CardVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=100)),
                ('variant_img', models.ImageField(upload_to='images')),
                ('order', models.PositiveIntegerField(default=0, editable=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.card')),
            ],
            options={
                'verbose_name_plural': 'Card variants',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NotebookImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_cover', models.ImageField(upload_to='images')),
                ('front_cover', models.ImageField(upload_to='images')),
                ('back_cover', models.ImageField(upload_to='images')),
                ('inside_front', models.ImageField(upload_to='images')),
                ('inside_back', models.ImageField(upload_to='images')),
                ('middle', models.ImageField(upload_to='images')),
                ('zoom_middle', models.ImageField(upload_to='images')),
                ('notebook', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.notebook')),
            ],
            options={
                'verbose_name_plural': 'Notebook images',
            },
        ),
    ]
