# Generated by Django 5.2.5 on 2025-09-02 10:47

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cart_image',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.upload_to),
        ),
    ]
