# Generated by Django 5.2.5 on 2025-08-23 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardinsert',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='catalog.size'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='size',
            name='orientation',
            field=models.CharField(blank=True, choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=10, null=True),
        ),
    ]
