# Generated by Django 5.2.5 on 2025-09-02 14:01

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='chosen_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.upload_to),
        ),
    ]
